export const DEFAULT_STORE = {
  store: {
    "document:document": {
      gridSize: 10,
      name: "",
      meta: {},
      id: "document:document",
      typeName: "document",
    },
    "pointer:pointer": {
      id: "pointer:pointer",
      typeName: "pointer",
      x: 0,
      y: 0,
      lastActivityTimestamp: 0,
      meta: {},
    },
    "page:page": {
      meta: {},
      id: "page:page",
      name: "Page 1",
      index: "a1",
      typeName: "page",
    },
    "camera:page:page": {
      x: 0,
      y: 0,
      z: 1,
      meta: {},
      id: "camera:page:page",
      typeName: "camera",
    },
    "instance_page_state:page:page": {
      editingShapeId: null,
      croppingShapeId: null,
      selectedShapeIds: [],
      hoveredShapeId: null,
      erasingShapeIds: [],
      hintingShapeIds: [],
      focusedGroupId: null,
      meta: {},
      id: "instance_page_state:page:page",
      pageId: "page:page",
      typeName: "instance_page_state",
    },
    "instance:instance": {
      followingUserId: null,
      opacityForNextShape: 1,
      stylesForNextShape: {},
      brush: { x: 0, y: 0, w: 0, h: 0 },
      zoomBrush: { x: 0, y: 0, w: 0, h: 0 },
      scribbles: [],
      cursor: {
        type: "default",
        rotation: 0,
      },
      isFocusMode: false,
      exportBackground: true,
      isDebugMode: false,
      isToolLocked: false,
      screenBounds: {
        x: 0,
        y: 0,
        w: 720,
        h: 400,
      },
      isGridMode: false,
      isPenMode: false,
      chatMessage: "",
      isChatting: false,
      highlightedUserIds: [],
      isFocused: true,
      devicePixelRatio: 2,
      insets: [false, false, false, false],
      isCoarsePointer: false,
      isHoveringCanvas: false,
      openMenus: [],
      isChangingStyle: false,
      isReadonly: false,
      meta: {},
      id: "instance:instance",
      currentPageId: "page:page",
      typeName: "instance",
    },
  },
  schema: {
    schemaVersion: 2,
    sequences: {
      "com.tldraw.store": 4,
      "com.tldraw.asset": 1,
      "com.tldraw.camera": 1,
      "com.tldraw.document": 2,
      "com.tldraw.instance": 25,
      "com.tldraw.instance_page_state": 5,
      "com.tldraw.page": 1,
      "com.tldraw.instance_presence": 5,
      "com.tldraw.pointer": 1,
      "com.tldraw.shape": 4,
      "com.tldraw.asset.bookmark": 2,
      "com.tldraw.asset.image": 4,
      "com.tldraw.asset.video": 4,
      "com.tldraw.shape.group": 0,
      "com.tldraw.shape.text": 2,
      "com.tldraw.shape.bookmark": 2,
      "com.tldraw.shape.draw": 2,
      "com.tldraw.shape.geo": 9,
      "com.tldraw.shape.note": 7,
      "com.tldraw.shape.line": 5,
      "com.tldraw.shape.frame": 0,
      "com.tldraw.shape.arrow": 5,
      "com.tldraw.shape.highlight": 1,
      "com.tldraw.shape.embed": 4,
      "com.tldraw.shape.image": 3,
      "com.tldraw.shape.video": 2,
      "com.tldraw.shape.container": 0,
      "com.tldraw.shape.element": 0,
      "com.tldraw.binding.arrow": 0,
      "com.tldraw.binding.layout": 0
    }
  },
}
